---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cinnguyenn
resources:
  - ../../base
  - ./virtual-service.yaml
  - ./hpa-api.yaml
images:
  - name: project
    newName: w255mids.azurecr.io/cinnguyenn/project
    newTag: "1b3eac1"
