---
name: GitHub Classroom Workflow

on:
  - push
  - workflow_dispatch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: self-hosted
    if: github.actor != 'github-classroom[bot]'

    steps:
      # Checkout
      - uses: actions/checkout@v4

      # Setup Dependencies
      - name: Setup yq
        uses: dcarbone/install-yq-action@v1.1.1
        with:
          version: "v4.40.5"

      - name: Setup Az CLI
        uses: pietrobolcato/install-azure-cli-action@main

      - name: Login to Azure
        id: login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_STUDENT }}

      - name: Setup Kubelogin
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: "v0.1.4"

      - name: "Setup node tooling"
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: "Setup redis cli"
        run: npm install -g redis-cli

      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v4

      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v4
        with:
          resource-group: "w255"
          cluster-name: "w255-aks"
          use-kubelogin: "true"

      - name: Setup kubeconfig
        run: |
          echo export KUBECONFIG="$KUBECONFIG" > inject-environments-from-action.sh
          chmod +x inject-environments-from-action.sh

      # Get Test Files
      - name: Download all autograder scripts
        run: |
          curl --header "X-API-KEY:${{ secrets.AUTOGRADER_API_AUTH_KEY }}" -s ${{ vars.AUTOGRADER_API_URL }}/static/lab4/L4-2-k8s.sh --output 2-k8s-lab.sh
          curl --header "X-API-KEY:${{ secrets.AUTOGRADER_API_AUTH_KEY }}" -s ${{ vars.AUTOGRADER_API_URL }}/static/lab4/L4-3-functionality.sh --output 3-functionality-lab.sh
          curl --header "X-API-KEY:${{ secrets.AUTOGRADER_API_AUTH_KEY }}" -s ${{ vars.AUTOGRADER_API_URL }}/static/project/P-1-acr.sh --output 1-acr-project.sh
          curl --header "X-API-KEY:${{ secrets.AUTOGRADER_API_AUTH_KEY }}" -s ${{ vars.AUTOGRADER_API_URL }}/static/project/P-2-k8s.sh --output 2-k8s-project.sh
          curl --header "X-API-KEY:${{ secrets.AUTOGRADER_API_AUTH_KEY }}" -s ${{ vars.AUTOGRADER_API_URL }}/static/project/P-3-functionality.sh --output 3-functionality-project.sh

      - name: Update lab files to reference project folder
        run: |
          search_string="./lab4/submission-namespace.yaml"
          replacement_string="./mlapi/submission-namespace.yaml"
          find . -type f -exec sed -i "s|$search_string|$replacement_string|g" {} +

      - name: Run Autograder Scripts
        uses: education/autograding@v1
